name: Run tests

on: [push]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.x'
        channel: 'stable'
      
    - name: Install Dart SDK 3.1.0
      run: |
        wget https://storage.googleapis.com/dart-archive/channels/stable/release/3.1.0/sdk/dartsdk-linux-x64-release.zip
        unzip dartsdk-linux-x64-release.zip
        export PATH="$PATH:`pwd`/dart-sdk/bin"
        dart --version
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Run tests
      run: flutter test
